add ur manager node
husarion/ur_ros pull request #1
Opened 2023-02-03 12:56 UTC by KmakD

2023-02-03 13:40 UTC, Kotochleb approved these changes

2023-02-03 13:40 UTC, Kotochleb commented on ur_bringup/src/ur_manager_node.py
> +from ur_dashboard_msgs.srv import GetRobotMode, IsInRemoteControl, Load, LoadRequest
```suggestion
from ur_dashboard_msgs.srv import GetRobotMode, Load, LoadRequest, IsInRemoteControl
```

2023-02-03 13:40 UTC, Kotochleb commented on ur_bringup/src/ur_manager_node.py
> +    def _ur_start_sequence(self):
```suggestion
    def _ur_start_sequence(self) -> None:
```

2023-02-03 13:41 UTC, Kotochleb requested changes
Fix it

2023-02-05 14:01 UTC, pkowalsk1 approved these changes

2023-02-05 14:01 UTC, merged